### ISSUE TITLE
Test sortPivots

### ISSUE THREAD

**Issue by NicoDelle** [NicoDelle/libMatrices#10]
Biogna testare sortPivots prima di fare il merge. Funziona sui seguenti testcases:
[[ 1, 2, 3, 4]
 [ 5 , 6, 7, 8]
 [ 9, 0,11,12] ],
[[1,1,1],
 [1,1,1],
 [1,1,1]]

**Comment by MarcoCrippa04** [comment]
Fixed sortPivots code and tested with different matrixs :)
